### ISSUE TITLE
Conflict e2e tests and storybook

### ISSUE THREAD

**Issue by SimoneIrato** [nisheed2440/stencil-storybook-wrapper#3]
I'm experiencing problems in running e2e tests with the wrapper.
Actually it looks like getResourcesUrl in stencil configs gets used also when in e2e test pointing to wrong folder, that is usually right for when developing with storybook

**Comment by equinusocio** [comment]
Same issue here. Running tests just after init the project i get these errors with e2e:

```
 ● my-component › renders

    Protocol error (Runtime.callFunctionOn): Target closed.

      at Promise (node_modules/puppeteer/lib/Connection.js:203:56)
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:202:12)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:97:75)
      at WaitTask.rerun (node_modules/puppeteer/lib/FrameManager.js:883:62)

  ● my-component › renders changes to the name data

    App did not load in allowed time. Please ensure the content loads a stencil application.

      at node_modules/@stencil/core/dist/testing/index.js:22513:19
      at fulfilled (node_modules/@stencil/core/dist/testing/index.js:42:58)


 RUNS  src/components/my-component/my-component.e2e.ts
 RUNS  plop/templates/component/component.e2e.ts

 FAIL  plop/templates/component/component.e2e.ts (5.634s)
  ● template-component › renders

    Protocol error (Runtime.callFunctionOn): Target closed.

      at Promise (node_modules/puppeteer/lib/Connection.js:203:56)
      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:202:12)
      at ExecutionContext.evaluateHandle (node_modules/puppeteer/lib/ExecutionContext.js:97:75)
      at WaitTask.rerun (node_modules/puppeteer/lib/FrameManager.js:883:62)

  ● template-component › renders changes to the name data

    App did not load in allowed time. Please ensure the content loads a stencil application.

      at node_modules/@stencil/core/dist/testing/index.js:22513:19
      at fulfilled (node_modules/@stencil/core/dist/testing/index.js:42:58)
```

**Comment by Nightbr** [comment]
Same issue, see this https://github.com/ionic-team/stencil/issues/1297
If I comment the `resourcesUrl` e2e tests runs fine.

**Comment by Nightbr** [comment]
This PR https://github.com/nisheed2440/stencil-storybook-wrapper/pull/4 fixes the thing 🎉 
Just add `cross-env STENCIL_ENV=dev` in package.json for test and test.watch and it works:

```
"test": "cross-env STENCIL_ENV=dev stencil test --spec --e2e",
"test.watch": "cross-env STENCIL_ENV=dev stencil test --spec --e2e --watchAll",
```
